### PR TITLE
Prepare updated postgres schema and migrations

### PR DESCRIPTION
**Pull request by irees**

### CODE REVIEW

**Comment by m4ng0** [comment]
Hi @irees, I'm sorry to "pollute" this PR, but since there isn't an issue section, I'll comment about a problem in the PostgreSQL schema here.
This PR is welcome because it solves a couple of problems in the PostgreSQL schema of the master branch, since it adds some missing fields in `current_operators ` and `public.current_operators_in_feed` tables (those fields are present in sqlite schema, thus tests pass). With this fix the `dmfr sync` command works well when using a PostgreSQL database (using the master code it fails).

However I think that the schema is still not complete: when finishing a feed import (`dmfr import`), the lib calls the function `AfterFeedVersionImport` that issues `SELECT` from various procedures (e.g. `tl_generate_feed_version_geometries`, see https://github.com/interline-io/transitland-lib/blob/update-schema/dmfr/importer/importer.go#L98-L105), that are not present in the pg schema, so the import gets rolled back.
I can see here https://github.com/interline-io/transitland-lib/blob/8c45aa6c925fec3081bd5a4e3006bd71f59c3e6b/tldb/sqlite.go#L33-L53 that for sqlite these procedures are substituted by a dummy func, but for PostgreSQL they are simply missing.

**Comment by CDimonaco** [comment]
Please @irees , can you give us an eta about the store procedures? We tried to found them in the old transitland repository but with no luck.

Thanks

**Comment by irees** [comment]
@m4ng0 @CDimonaco Oh, hi! I'm working on another branch that removes the need for any stored procedures in postgres. I'm testing it now and it will be in the next release tag.

**Comment by CDimonaco** [comment]
Thanks @irees if can be helpful, we released a tool in order to generate the route shapes from trips, we use it in production, https://github.com/phoops/transitland-route-geometry-generator

**Comment by irees** [comment]
@CDimonaco It's always cool to see what people are doing with this tool! The code I merged in #138 (still testing a little more before a 0.9 release) includes a replacement for the postgres functions that I hadn't released. One part of this is populating `tl_route_geometries` with the longest shape for each route (in `geometry`) and a MultiLineString that is an ensemble of representative shapes for each route, in both directions (`combined_geometry`).

**Pull request merged**
